# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

env:
  PORT=${{ secrets.PORT }}
  HOST=${{ secrets.HOST }}
  NODE_ENV=${{ secrets.NODE_ENV }}
  APP_KEY=${{ secrets.APP_KEY }}
  DRIVE_DISK=${{ secrets.DRIVE_DISK }}
  SESSION_DRIVER=${{ secrets.SESSION_DRIVER }}
  CACHE_VIEWS=${{ secrets.CACHE_VIEWS }}
  DB_CONNECTION=${{ secrets.DB_CONNECTION }}
  PG_HOST=${{ secrets.PG_HOST }}
  PG_PORT=${{ secrets.PG_PORT }}
  PG_USER=${{ secrets.PG_USER }}
  PG_PASSWORD=${{ secrets.PG_PASSWORD }}
  PG_DB_NAME=${{ secrets.PG_DB_NAME }}

jobs:


  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Create and Populate .env file
        run: echo $APP_KEY

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
